dockerfiles/rpm-pkg.dev
go.mod
go.sum
scripts/build-deb.sh
scripts/build-rpm.sh

- use almalinux:8 so we get an old glibc depenency
- build separate source and binary specs, since we get an up-to-date golang, and building needs system golang
- tested on fedora42, seems to work
- changelog tool expanded for rpm (in addition to deb)

build: initial scripts for build/x-compile of rpms

---

proto-src/lcl/secret_key.snowp
proto/lcl/secret_key.go

- remove some aged comments about not needing the Account field, which we do

skm: clean out old keychain V1 material

---

lib/core/constants.go
lib/team/core.go

- there are degenerate cases where there are 64k or so role types, that would make for a very bad experience
- limit the # to 16 for now and if that proves insufficient, we can revisit this limitation
- addresses #34
- it's hard to test it, so no tests just yet
- another attempt at a fix might be to have this check kick in higher up the stack, so we have GlobalContexts etc to check against
- but then we have to worry about client and server having different values configured for the limit

teams: limit # of roles per team to 16

---

changelog.yml
client/foks/cmd/help.go
client/foks/cmd/team.go
client/libclient/team_minder_add.go
lib/core/rewrap.go

- add a separate page for `foks help roles`
- flesh out examples sections
- close issue #14

cli: fix docs for `team add` and `team change-roles`

---

changelog.yml
lib/core/crypto.go
lib/core/errors.go
lib/core/sigs.go
lib/core/sigs2.go
lib/core/snowp.go
lib/core/snowp_test.go

- assert canonical on the verify path of sig2
- assert canonical on the encode path for producing signatures
- assert prefixedhash, hash and hmac are also canonical encodings
- close #38

core: verify canonical snowpack encodings

---

scripts/build-rpm.sh

- i'm not too psyched about this since it doesn't allow us to pin down a version, etc
- would prefer a docker-based approach, but grew frustrated trying to get gnugp to work inside the docker
- will revisit

build: use brew-based rpm --addsign to sign RPMs

---

client/libclient/user_loader.go
integration-tests/lib/user_loader_test.go
server/shared/resolve_username.go

- repro of the issue in user_loader_test
- close issue #52, we might not get usernames back from the server if we previously did previously
- implement resolution on a local host if permitted via local_view_permission, came up in testing
- might actually break existing code paths, need to check carefully

user_loader: fix panic in some resolve username cases

---

changelog.yml
client/foks/cmd/kv.go
client/libclient/errors.go
client/libclient/gitbash.go

- err on the side of caution and don't rewrite a:/b/c -> /a/b/c since we don't know if we got here only becuase our EXEPATH check didn't work
- this is slightly confusing as the user will have to `kv ls //a/b` but will not need to in the case of `kv ls /allo/eee` (since the second path component has >1 characters and the first has exactly one character)
- we might revisit this later
- close #62

cli: actually invert git-bash style path rewrites

---

client/foks/cmd/cmd.go
client/foks/cmd/kv.go
pkg/choco/.gitignore
pkg/choco/ReadMe.md
pkg/choco/_TODO.txt
pkg/choco/foks.nuspec
pkg/choco/tools/LICENSE.txt
pkg/choco/tools/VERIFICATION.txt
pkg/choco/tools/chocolateybeforemodify.ps1
pkg/choco/tools/chocolateyinstall.ps1
pkg/choco/tools/chocolateyuninstall.ps1
scripts/choco-gen.bash
scripts/choco-push.bash

- script automates packaging based on latest tag in git and git release of binaries
- also run the choco binary if available; for now, we'll be doing this on an actual windows host, after spending multiple hours trying to get it to run on linux in a docker
- upload nuget file to foks kv
- fix output of `foks kv link`
- alias for `foks kv link`
- push script
- close #56
- likely we'll revisit

win: chocolatey support

---

changelog.yml
server/kv-store/root.go
server/kv-store/server.go

- only admin or above can make a root node on a KV store, for now
- maybe change this, but give a better error in this case
- Close #67
- There's another part of #67 we do not close

kv: better permission denied message mkdir("/")

---

changelog.yml
client/libclient/plist_darwin.go

- this will capture strack traces on panic
- also will capture stray output to stderr or stdout
- close #75

macOS: redirect stdout and stderr to logs

---

client/agent/srv.go
client/foks/cmd/cmd.go
client/foks/cmd/nag.go
client/libclient/compat.go
client/libclient/nag.go
dockerfiles/foks-tool.dev
integration-tests/cli/nag_test.go
lib/core/version.go
make/server.mk
scripts/cross-compile-foks-tool.bash
server/foks-tool/main.go
server/foks-tool/standup.go
server/foks-tool/version.go

- for the curl script, interactive mode will deal with the weirdness around passing params through to the script
- for now, since docker is too annoying, we'll release static linux binaries along with releases
- server-install.sh script is tested
- run with: `/usr/bin/env bash <(curl -fsSL https://pkgs.foks.pub/server-install.sh)`
- close #89

standup: interactive mode; binary foks-tool release

---

changelog.yml
client/foks/cmd/ui/view.go
client/libclient/home.go
conf/srv/foks-docker-compose.jsonnet
dockerfiles/foks-server.dev
dockerfiles/foks-tool.dev
make/server.mk
proto-src/lib/config.snowp
proto/lib/config.go
proto/lib/extras.go
proto/lib/server.go
server/foks-tool/standup.go
server/foks-tool/viewership.go
server/shared/viewership.go
server/sql/embed.go
server/sql/foks_server_config.sql
server/sql/patches/foks_server_config/p1.sql

- get/set of viewership mode via CLI
- styling tweaks to standup and signup (for recoring videos)
- FOKS_HOME feature, can specify foks home dir via environment variable without messing with $HOME, which impacts system functioning
- add a standalone basic server type
- DB patch included for foks_server_config database
- rewrap text where necessary
- fix lint errors in standup
- macros for pushing tools and server to github and container registry
- support kv store on standalone host
- close #93

srv: various fixes for `standup`-generate hosts

---

client/libclient/team_loader.go
client/libclient/team_minder_add.go
integration-tests/cli/team_test.go
integration-tests/cli/web_vanity_test.go
integration-tests/lib/open_view_test.go
proto-src/lib/config.snowp
proto/lib/config.go
proto/lib/extras.go
server/foks-tool/standup.go
server/foks-tool/viewership.go
server/shared/perms.go
server/shared/resolve_username.go
server/shared/user_loader.go
server/sql/embed.go
server/sql/foks_server_config.sql
server/sql/patches/foks_server_config/p2.sql
server/web/lib/vhosts.go

- eventually we're going to have OpenToWorld, which means even remote users can load users on this host
- OpenToAll seems confusing and similar to OpenToWorld, so proactively change it to Open now
- close #98

srv: rename OpenToAll -> Open

---

make/client.mk
scripts/macos-compile.bash

- parallel build for macos-brew, which is the same as regular but with the `brew` packaging tag
- close #110

macos: special brew build

---

changelog.yml
client/agent/srv.go
client/libclient/context.go
client/libclient/globals.go
client/libclient/log_rotate.go
integration-tests/cli/log_test.go
lib/core/path.go

- simple log rotation for the client, without any real tunable constants, but we might consider more in the future, like:
- tunable time, tunable # of logs kept, and tunable gzip compression of old logs
- gzip happens now all the time on rotated logs
- partial close of #119, we still need to build logsend

cli: log rotation

---

scripts/srv/deploy.sh
server/shared/cks.go

- fix deploy script for foks.app-style deploys after #159 fix
- tested and deployed to foks.app
- close #161

autocert: on refresh, update the row, and stomp over the old cert

---

changelog.yml
client/agent/user.go
client/foks/cmd/key.go
client/foks/cmd/ui/switch.go
client/libclient/active_user.go
client/libclient/all_users.go
client/libclient/rotate_mgr.go
integration-tests/cli/remove_test.go
proto-src/lcl/user.snowp
proto/lcl/user.go

- removes a yubikey or backup key from your key list
- interactive or flag-driven mode
- reuse a lot of machinery from `foks key switch`
- add a test
- close #167
- will be in v0.1.2

cli: `foks key remove`

---

scripts/srv/config.bash

This fixes a typo in `scripts/srv/config.bash`

Fix a typo in server `config.bash` script

---

changelog.yml
client/foks/cmd/kv.go
client/libkv/minder.go
client/libkv/rest.go
integration-tests/cli/rest_test.go
proto-src/lcl/kv.snowp
proto/lcl/kv.go
proto/lib/extras.go

- in REST mode, say whether the entry is a file, dir, symlink; look in the "type" field
- test new REST ls fields
- options for kv ls: -l, -F, and -U
- will be released in v0.1.3
- close #190

cli: improved KV ls behavior

---

changelog.yml
client/foks/cmd/kv.go

- for now, simplify, don't support --mkdir-p or --team for start REST kv
- in the future, there might be a need for better granularity and privilege-stripping for this feature
- for now, keep it simple
- close #191
- released in v0.1.3

cli: clean up REST start/stop flags

---

changelog.yml
client/foks/cmd/common_ui/user.go

- give better information on device names
- include bot-tokens
- yubikey device info in a more consistent form
- code-cleanup
- close #193
- released in v0.1.3

cli: fix `key switch` and `key remove` UIs

---

changelog.yml
client/foks/cmd/key.go
client/foks/cmd/parse.go
client/libclient/all_users.go
integration-tests/cli/revoke_test.go
proto-src/lcl/user.snowp
proto-src/lib/common.snowp
proto/lcl/user.go

- no more query-by-key-genus or role
- provide an FQU, which works if not ambiguous
- if ambiguous, you can also provide a keyID
- no ability to just use a KeyID though it should work, so maybe we add this late
- close #208
- released in v0.1.3

cli: simplify args to `key switch` and `key remove`
